export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ background: '#1a1a1d', color: '#f5f5f5', margin: 0, overflow: 'hidden' }}>{children}</body>
    </html>
  )
}
